* Ссылки
#+begin_src 
{Текст ссылки|link_dest} {var_int = 1 var_text = "some text" +flag_var_to_add -flag_var_to_remeve}
#+end_src
Блок переменных необязателен. Можно разбивать его переносами строки для читаемости.
* Условные выражения
#+begin_src
?var < 10?
Текст вставится только если var определен и < 10
!other_var = 10!
Иначе если other_var = 10
!!
Если ни один вариант не подошел
&&
#+end_src
Можно писать и в одну строчку.
#+begin_src 
?flag? текст !! другой текст &&
#+end_src
Это просто текстовая подстановка, выбранная ветка вставляется в текст, остальне вырезаются.
* Подстановка переменных
#+begin_src
На двери было [locks] замков.
Взломать ее стоило [coins_in_wallet + 3 | 5] монет. Мне не хватало совсем немного...
#+end_src
После | идет значение, подставляемое если одна из переменных в выражении не назначена.
Если в переменной строка (рекомендуется избегать таких случаев) ее можно сложить с другой строкой. Число и строку сложить нельзя, это вам не джаваскрипт.
Подстановка выполняется до всех остальных операций, поэтому можно использовать ее в условиях или адресе ссылки.
* Пример комбинирования операций
#+begin_src
?bytecoins_in_vallet < 10?
{Попытаться украсть чип|[thievery + 180]} {?thievery = 0? +wounded &&}
!!
{Купить чип|451} {bytecoins_in_vallet = [bytecoins_in_vallet - 10] +has_chip}
&&
#+end_src
* Порядок операций
1. Подстановка переменных
2. Подстановка условий
3. Обработка ссылок
