* Что сделать надо
** Переменные
Хранить в базе данных, привязать к аккаунту
*** Флаг видимости
Некоторые переменные будут видимы игроку, например предметы и важные значения. Остальные будут скрыты.
** Аккаунты
Чтобы не хранить переменные в куки
** Язык разметки
Чтобы переменные были полезными
** Странички для модерирования
Возможность откатывать изменения, закрывать странички для редактирования и.т.д.
* Что сделать можно
** Темная тема? И в общем немного оформления.
** Более удобный редактор параграфов
Подсветка, шаблоны. Видимо на JS.
** Режим свободного просмотра
Будет полезно для писателей — смотреть все, что есть чтобы писать непротиворечивую историю.
** Просмотр истории редактирования
** Бот уведомляющий модераторов о новой страничке
** Анализатор графа вариантов который показывает, с какими значениями можно прийти сюда
* Маловероятно
** Достижения??
Не уверен, есть ли в них смысл.
** Выгрузка всего квеста в файл, возможность переключаться
Не совсем та идея, что изначально закладывалась.

* Описание идеи
Текстовый квест, похожий по структуре на классические книги-игры. Отличеатся тем, что дает возможность всем игрокам редактировать страницы и развивать сюжет. К этому будет добавлена система переменных, которые добавят больше нелинейности. Для этого будет система аккаунтов, хранящих прогресс игрока. Для написания истории, меняющейся в зависимости от значений переменных, мы придумаем язык разметки параграфов. Очевидно нужна будет история редактирования и инструменты модерации, похоже как на вики-проектах.
