start: something+

?special: subst
        | if
        | link

?something: special
          | newline
          | text

newline: EMPTY_LINE
EMPTY_LINE: /[ \t\f]*\r?\n/

subst: "(%" expr "%)"

expr: sum
string: /\"[^\"]*\"/

?sum: product
   | sum "+" product -> sum
   | sum "-" product -> diff
?product: atom
       | product "*" atom -> mult
       | product "/" atom -> div
?atom: NUMBER -> number
    | "-" atom -> neg
    | VARNAME -> var
    | "(" sum ")"


if: "(?" conditional "?)" _WS* then elif* else? "(;;)"
elif: "(!" conditional "!)" something*
else: "(!!)" something*
then: something*

?conditional: cond_or

?cond_or: cond_and
        | cond_or "|" cond_and -> or

?cond_and: logical_atom
        | cond_and "&" logical_atom -> and

?logical_atom: VARNAME -> flagvar
             | expr comp expr -> comp

!?comp:"<" | ">" | "=" | "<=" | ">="


link: "((" text ";" NUMBER "))" varblock?
varblock: "((" _WS* (varset "," _WS*)* varset _WS* "))"
?varset: "+" VARNAME -> flag
       | "-" VARNAME -> unflag
       | VARNAME "=" expr -> set
       | VARNAME "=" string -> set


VARNAME: (LETTER|"_") (LETTER|DIGIT|"_")*
LETTER: "a".."z" | "A".."Z" | "а".."я" | "А".."Я"
text: /(?:(?!\(\(|\)\)|\(\?|\?\)|\(!|!\)|\(;;\)|\(%|%\)|; *\d+)[^\r\n])+/

_SPC: WS_INLINE
_N: /\r?\n/

%import common.SIGNED_INT -> NUMBER
%import common.DIGIT
%import common.WS_INLINE
%import common.WS -> _WS
%ignore WS_INLINE
